name: user_articles
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  retrofit: ^3.3.1
  bloc: ^8.1.2
  get_it: ^7.6.7
  injectable: ^2.3.2

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
